# Generated by Django 4.2.10 on 2024-03-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_recipe_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='blog.comment'),
        ),
    ]
